<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\DocQuery.Infrastructure.Persistence\DocQuery.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\DocQuery.Tests.Common\DocQuery.Tests.Common.csproj" />
  </ItemGroup>

</Project>
