<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DocQuery.ServiceDefaults\DocQuery.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DocQuery.Application\DocQuery.Application.csproj" />
    <ProjectReference Include="..\DocQuery.Infrastructure\DocQuery.Infrastructure.csproj" />
  </ItemGroup>

</Project>
