<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>docquery-workers-embedding</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DocQuery.ServiceDefaults\DocQuery.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DocQuery.Application\DocQuery.Application.csproj" />
    <ProjectReference Include="..\DocQuery.Infrastructure\DocQuery.Infrastructure.csproj" />
    <ProjectReference Include="..\DocQuery.Infrastructure.Persistence\DocQuery.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
