<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocQuery.Application\DocQuery.Application.csproj" />
  </ItemGroup>

</Project>
